config/routes.rb
Growstuff::Application.routes.draw do

  get '/robots.txt' => 'robots#robots'

  resources :plant_parts

  devise_for :members, :controllers => { :registrations => "registrations", :passwords => "passwords" }
  devise_scope :member do 
    get '/members/unsubscribe/:message' => 'members#unsubscribe', :as => 'unsubscribe_member'
  end

  resources :members 

  resources :photos

  resources :authentications, :only => [:create, :destroy]

  resources :plantings
  get '/plantings/owner/:owner' => 'plantings#index', :as => 'plantings_by_owner'
  get '/plantings/crop/:crop' => 'plantings#index', :as => 'plantings_by_crop'

  resources :gardens
  get '/gardens/owner/:owner' => 'gardens#index', :as => 'gardens_by_owner'

  resources :seeds
  get '/seeds/owner/:owner' => 'seeds#index', :as => 'seeds_by_owner'
  get '/seeds/crop/:crop' => 'seeds#index', :as => 'seeds_by_crop'

  resources :harvests
  get '/harvests/owner/:owner' => 'harvests#index', :as => 'harvests_by_owner'
  get '/harvests/crop/:crop' => 'harvests#index', :as => 'harvests_by_crop'

  resources :posts
  get '/posts/author/:author' => 'posts#index', :as => 'posts_by_author'

  resources :scientific_names
  resources :alternate_names

  get 'crops/wrangle' => 'crops#wrangle', :as => 'wrangle_crops'
  get 'crops/hierarchy' => 'crops#hierarchy', :as => 'crops_hierarchy'
  get 'crops/search' => 'crops#search', :as => 'crops_search'
  resources :crops

  resources :comments
  resources :roles
  resources :forums
  resources :notifications do
    get 'reply', on: :member
  end

  resources :follows, :only => [:create, :destroy]
  get '/members/:login_name/follows' => 'members#view_follows', :as => 'member_follows'
  get '/members/:login_name/followers' => 'members#view_followers', :as => 'member_followers'


  get '/places' => 'places#index'
  get '/places/search' => 'places#search', :as => 'search_places'
  get '/places/:place' => 'places#show', :as => 'place'

  # everything for paid accounts etc
  resources :account_types
  resources :accounts
  resources :orders
  get 'orders/:id/checkout' => 'orders#checkout', :as => 'checkout_order'
  get 'orders/:id/complete' => 'orders#complete', :as => 'complete_order'
  get 'orders/:id/cancel' => 'orders#cancel', :as => 'cancel_order'

  resources :order_items
  resources :products

  get "home/index"
  root :to => 'home#index'

  get 'auth/:provider/callback' => 'authentications#create'


  get '/policy/:action' => 'policy#:action'

  get '/support' => 'support#index'
  get '/support/:action' => 'support#:action'

  get '/about' => 'about#index'
  get '/about/:action' => 'about#:action'

  get '/shop' => 'shop#index'
  get '/shop/:action' => 'shop#:action'

  comfy_route :cms_admin, :path => '/admin/cms'
  get '/admin/orders' => 'admin/orders#index'
  get '/admin/orders/:action' => 'admin/orders#:action'
  get '/admin' => 'admin#index'
  get '/admin/newsletter' => 'admin#newsletter', :as => :admin_newsletter
  get '/admin/:action' => 'admin#:action'

# CMS stuff  -- must remain LAST
  comfy_route :cms, :path => '/', :sitemap => false

end

app/views/notifier/_signature.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']

%p
  The #{site_name} team.
  %br/
  =link_to root_url, root_url

app/views/notifier/crop_request_approved.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']
%p Hello #{@member.login_name},

%p
  Your request for the new crop: #{link_to @crop.name, crop_url(@crop)} has been approved! Thank you for helping us make our listing ever more complete!

%ul
  %li
    = link_to "Plant #{@crop.name}", new_planting_url(crop_id: @crop.id)
  %li
    = link_to "Harvest #{@crop.name}", new_harvest_url(crop_id: @crop.id)
  %li
    = link_to "Stash seeds for #{@crop.name}", new_seed_url(crop_id: @crop.id)

= render :partial => 'signature'

app/views/notifier/crop_request_rejected.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']
%p Hello #{@member.login_name},

%p
  We're sorry, but your request for the new crop: #{link_to @crop.name, crop_url(@crop)} has been rejected for the following reason: #{@crop.rejection_explanation}

= render :partial => 'signature'

app/views/notifier/new_crop_request.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']

%p Hello #{@member.login_name},

%p 
  #{@request.requester.login_name} has requested a new crop on #{site_name}.

%ul
  %li Name: #{@request.name}
  %li Wikipedia URL: #{@request.en_wikipedia_url.present? ? @request.en_wikipedia_url : "not specified"}
  %li Notes: #{@request.request_notes}

%p
  As a crop wrangler, you can #{link_to "approve or reject this request", edit_crop_url(@request)}.

%p
  Or, discuss this and other crop wrangling issues in our #{link_to "crop wrangling forum", "http://talk.growstuff.org/c/crop-wrangling"}.

%p
  Thanks for your help!

= render :partial => 'signature'

app/views/notifier/notify.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']
%p Hello #{@notification.recipient.login_name},

%p
  You have received a message from
  = link_to @notification.sender.login_name, member_url(@notification.sender)
  on #{site_name} at #{@notification.created_at}
  - if @notification.post
    in response to
    = link_to @notification.post.subject, post_url(@notification.post)
  \.
%blockquote
  :growstuff_markdown
    #{strip_tags @notification.body}

%p
  = link_to "Reply to this message", @reply_link
  %br/
  = link_to "View this message in your inbox", notification_url(@notification)
  %br/
  = link_to "Unsubscribe from direct message notifications", unsubscribe_member_url(@signed_message)
  from these notifications

= render :partial => 'signature'

app/views/notifier/planting_reminder.html.haml
- site_name = ENV['GROWSTUFF_SITE_NAME']
%p Hello #{@member.login_name},

%h2 What's new in your garden?

%p

- if @member.plantings.size == 0
  %p
    #{site_name} lets you track what food you're growing
    in your garden and see what other people near you are planting too.
  %p
    = link_to "Get started now", new_planting_url
    by planting your first crop.

- else
  %p
    The most recent plantings you've told us about are:

  %ul
  - @plantings.each do |p|
    %li
      = link_to p, planting_url(p)
      planted
      = distance_of_time_in_words(p.created_at, Time.zone.now)
      ago.

  %p
    = link_to "Plant something new", new_planting_url
    to keep your garden records up to date.

%h2 Your recent harvests

- if @member.harvests.size == 0
  %p
    #{site_name} helps you keep track of what you
    harvest from your garden.  Record what food you've grown
    and see what other people near you are harvesting, too.

  %p
    = link_to "Get started now", new_harvest_url
    by tracking your first harvest.

- else
  According to our records, the last few things you harvested were:

  %ul
  - @harvests.each do |h|
    %li
      = link_to h, harvest_url(h)
      harvested
      = distance_of_time_in_words(h.created_at, Time.zone.now)
      ago.

  %p
    Harvested anything else lately?
    = link_to "Track your harvests here.", new_harvest_url

%h2
  See you soon on #{site_name}!

= render :partial => 'signature'

%hr/
%p
  Don't want to get these emails any more?
  = link_to "Unsubscribe from planting reminders", unsubscribe_member_url(@signed_message)