config/routes.rb
Growstuff::Application.routes.draw do

  get '/robots.txt' => 'robots#robots'

  resources :plant_parts

  devise_for :members, :controllers => { :registrations => "registrations", :passwords => "passwords" }
  devise_scope :member do 
    get '/members/unsubscribe/:message' => 'members#unsubscribe', :as => 'unsubscribe_member'
  end

  resources :members 

  resources :photos

  resources :authentications, :only => [:create, :destroy]

  resources :plantings
  get '/plantings/owner/:owner' => 'plantings#index', :as => 'plantings_by_owner'
  get '/plantings/crop/:crop' => 'plantings#index', :as => 'plantings_by_crop'

  resources :gardens
  get '/gardens/owner/:owner' => 'gardens#index', :as => 'gardens_by_owner'

  resources :seeds
  get '/seeds/owner/:owner' => 'seeds#index', :as => 'seeds_by_owner'
  get '/seeds/crop/:crop' => 'seeds#index', :as => 'seeds_by_crop'

  resources :harvests
  get '/harvests/owner/:owner' => 'harvests#index', :as => 'harvests_by_owner'
  get '/harvests/crop/:crop' => 'harvests#index', :as => 'harvests_by_crop'

  resources :posts
  get '/posts/author/:author' => 'posts#index', :as => 'posts_by_author'

  resources :scientific_names
  resources :alternate_names

  get 'crops/wrangle' => 'crops#wrangle', :as => 'wrangle_crops'
  get 'crops/hierarchy' => 'crops#hierarchy', :as => 'crops_hierarchy'
  get 'crops/search' => 'crops#search', :as => 'crops_search'
  resources :crops

  resources :comments
  resources :roles
  resources :forums
  resources :notifications do
    get 'reply', on: :member
  end

  resources :follows, :only => [:create, :destroy]
  get '/members/:login_name/follows' => 'members#view_follows', :as => 'member_follows'
  get '/members/:login_name/followers' => 'members#view_followers', :as => 'member_followers'


  get '/places' => 'places#index'
  get '/places/search' => 'places#search', :as => 'search_places'
  get '/places/:place' => 'places#show', :as => 'place'

  # everything for paid accounts etc
  resources :account_types
  resources :accounts
  resources :orders
  get 'orders/:id/checkout' => 'orders#checkout', :as => 'checkout_order'
  get 'orders/:id/complete' => 'orders#complete', :as => 'complete_order'
  get 'orders/:id/cancel' => 'orders#cancel', :as => 'cancel_order'

  resources :order_items
  resources :products

  get "home/index"
  root :to => 'home#index'

  get 'auth/:provider/callback' => 'authentications#create'


  get '/policy/:action' => 'policy#:action'

  get '/support' => 'support#index'
  get '/support/:action' => 'support#:action'

  get '/about' => 'about#index'
  get '/about/:action' => 'about#:action'

  get '/shop' => 'shop#index'
  get '/shop/:action' => 'shop#:action'

  comfy_route :cms_admin, :path => '/admin/cms'
  get '/admin/orders' => 'admin/orders#index'
  get '/admin/orders/:action' => 'admin/orders#:action'
  get '/admin' => 'admin#index'
  get '/admin/newsletter' => 'admin#newsletter', :as => :admin_newsletter
  get '/admin/:action' => 'admin#:action'

# CMS stuff  -- must remain LAST
  comfy_route :cms, :path => '/', :sitemap => false

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorize_resource

  def index

    # we were previously generating a lot of instance variables like
    # @members_count and @interesting_crops in here, but now we call
    # the relevant class methods directly in the view, so that fragment
    # caching will be effective.

    respond_to do |format|
      format.html # index.html.haml
    end
  end

end

app/views/home/_blurb.html.haml
.col-md-12

%h1= ENV['GROWSTUFF_SITE_NAME']

.row
  .col-md-8.info
    %p= t('.intro', site_name: ENV['GROWSTUFF_SITE_NAME'])

    = render :partial => 'stats'
  .col-md-4.signup
    %p= t('.perks')
    %p= link_to(t('.sign_up'), new_member_registration_path, :class => 'btn btn-primary btn-lg')
    %p
      %small
        = t('.already_html', sign_in: link_to(t('.sign_in_linktext'), new_member_session_path))

app/views/home/_crops.html.haml
.row
  .col-md-8
    - cache cache_key_for(Crop, 'interesting'), :expires_in => 1.day do
      %h2= t('.our_crops')
      .hidden-xs
        - Crop.interesting.first(8).each do |c|
          .col-md-3
            = render :partial => 'crops/thumbnail', :locals => { :crop => c }
      .visible-xs
        - Crop.interesting.first(3).each do |c|
          .col-md-3
            = render :partial => 'crops/thumbnail', :locals => { :crop => c }

  .col-md-4.hidden-xs
    - cache cache_key_for(Planting) do
      %h2= t('.recently_planted')
      = render :partial => 'plantings/list', :locals => { :plantings => Planting.interesting.first(6) }

.row
  .col-md-12
    - cache cache_key_for(Crop, 'recent') do
      %p{ :style => 'margin-top: 11.25px' }
        %strong
          #{t('.recently_added')}:
        != Crop.recent.limit(12).map {|c| link_to(c, c) }.join(", ")

    %p.text-right
      =link_to "#{t('.view_all')} »", crops_path

app/views/home/_discuss.html.haml
%h2= t('.discussion')

- posts = Post.limit(6)
- if posts
  =render :partial => "posts/summary", :locals => { :posts => posts, :howmany => 6 }

- cache cache_key_for(Forum) do
  - forums = Forum.all
  - if forums
    %ul.list-inline
      %li
        %strong #{t('.forums')}:
      - forums.each do |f|
        %li= link_to f.name, f

%p.text-right
  = link_to "#{t('.view_all')} »", posts_path

app/views/home/_members.html.haml
- cache cache_key_for(Member) do
  .hidden-xs
    - members = Member.interesting.first(6)
    - if members.present?
      %section
      %h2= t('.title')

      .member-cards
        - members.each do |m|
          = render :partial => "members/thumbnail", :locals => { :member => m }

      %p.text-right
        = link_to "#{t('.view_all')} »", members_path

app/views/home/_seeds.html.haml
- seeds = Seed.interesting.first(6)
- if seeds.present?

  %h2= t('.title')

  - cache cache_key_for(Seed) do
    - if seeds.size > 0

      %table.table.table-striped
        %tr
          %th= t('.owner')
          %th= t('.crop')
          %th.hidden-xs.hidden-sm= t('.description')
          %th= t('.trade_to')
          %th= t('.from')
          %th

        - seeds.each do |seed|
          %tr
            %td= link_to seed.owner.login_name, seed.owner
            %td= link_to seed.crop.name, seed.crop
            %td.hidden-xs.hidden-sm= truncate(seed.description, :length => 40, :separator => ' ')
            %td= seed.tradable? ? seed.tradable_to : ''
            %td
              - if seed.tradable?
                = seed.owner.location.blank? ? t('.unspecified') : truncate(seed.owner.location, :length => 25, :separator => ', ')
            %td= link_to t('.details'), seed, :class => 'btn btn-default btn-xs'

  %p.text-right
    = link_to "#{t('.view_all')} »", seeds_path

app/views/home/_stats.html.haml
- cache("homepage_stats") do
  %p.stats
    = t('.message_html', { member: link_to(t('.member_linktext', count: Member.confirmed.size.to_i), members_path),
                           number_crops: link_to(t('.number_crops_linktext', count: Crop.count.to_i), crops_path),
                           number_plantings: link_to(t('.number_plantings_linktext', count: Planting.count.to_i), plantings_path), 
                           number_gardens: link_to(t('.number_gardens_linktext', count: Garden.count.to_i), gardens_path) })

app/views/home/index.html.haml
.row
  .col-md-12
    - if member_signed_in?
      %h1= t('.welcome', site_name: ENV['GROWSTUFF_SITE_NAME'], member_name: current_member)

      = render :partial => 'stats'
      %p
        .btn-group
          = link_to t('.plant'), new_planting_path, :class => 'btn btn-default'
          = link_to t('.harvest'), new_harvest_path, :class => 'btn btn-default'
          = link_to t('.add_seeds'), new_seed_path, :class => 'btn btn-default'
          = link_to t('.post'), new_post_path, :class => 'btn btn-default'

    - else
      .hidden-xs
        .jumbotron
          = render :partial => 'blurb'
      .visible-xs
        = render :partial => 'blurb'

    = render :partial => 'crops'
    = render :partial => 'seeds'
    = render :partial => 'members'
    = render :partial => 'discuss'