config/routes.rb
Growstuff::Application.routes.draw do

  get '/robots.txt' => 'robots#robots'

  resources :plant_parts

  devise_for :members, :controllers => { :registrations => "registrations", :passwords => "passwords" }
  devise_scope :member do 
    get '/members/unsubscribe/:message' => 'members#unsubscribe', :as => 'unsubscribe_member'
  end

  resources :members 

  resources :photos

  resources :authentications, :only => [:create, :destroy]

  resources :plantings
  get '/plantings/owner/:owner' => 'plantings#index', :as => 'plantings_by_owner'
  get '/plantings/crop/:crop' => 'plantings#index', :as => 'plantings_by_crop'

  resources :gardens
  get '/gardens/owner/:owner' => 'gardens#index', :as => 'gardens_by_owner'

  resources :seeds
  get '/seeds/owner/:owner' => 'seeds#index', :as => 'seeds_by_owner'
  get '/seeds/crop/:crop' => 'seeds#index', :as => 'seeds_by_crop'

  resources :harvests
  get '/harvests/owner/:owner' => 'harvests#index', :as => 'harvests_by_owner'
  get '/harvests/crop/:crop' => 'harvests#index', :as => 'harvests_by_crop'

  resources :posts
  get '/posts/author/:author' => 'posts#index', :as => 'posts_by_author'

  resources :scientific_names
  resources :alternate_names

  get 'crops/wrangle' => 'crops#wrangle', :as => 'wrangle_crops'
  get 'crops/hierarchy' => 'crops#hierarchy', :as => 'crops_hierarchy'
  get 'crops/search' => 'crops#search', :as => 'crops_search'
  resources :crops

  resources :comments
  resources :roles
  resources :forums
  resources :notifications do
    get 'reply', on: :member
  end

  resources :follows, :only => [:create, :destroy]
  get '/members/:login_name/follows' => 'members#view_follows', :as => 'member_follows'
  get '/members/:login_name/followers' => 'members#view_followers', :as => 'member_followers'


  get '/places' => 'places#index'
  get '/places/search' => 'places#search', :as => 'search_places'
  get '/places/:place' => 'places#show', :as => 'place'

  # everything for paid accounts etc
  resources :account_types
  resources :accounts
  resources :orders
  get 'orders/:id/checkout' => 'orders#checkout', :as => 'checkout_order'
  get 'orders/:id/complete' => 'orders#complete', :as => 'complete_order'
  get 'orders/:id/cancel' => 'orders#cancel', :as => 'cancel_order'

  resources :order_items
  resources :products

  get "home/index"
  root :to => 'home#index'

  get 'auth/:provider/callback' => 'authentications#create'


  get '/policy/:action' => 'policy#:action'

  get '/support' => 'support#index'
  get '/support/:action' => 'support#:action'

  get '/about' => 'about#index'
  get '/about/:action' => 'about#:action'

  get '/shop' => 'shop#index'
  get '/shop/:action' => 'shop#:action'

  comfy_route :cms_admin, :path => '/admin/cms'
  get '/admin/orders' => 'admin/orders#index'
  get '/admin/orders/:action' => 'admin/orders#:action'
  get '/admin' => 'admin#index'
  get '/admin/newsletter' => 'admin#newsletter', :as => :admin_newsletter
  get '/admin/:action' => 'admin#:action'

# CMS stuff  -- must remain LAST
  comfy_route :cms, :path => '/', :sitemap => false

end

app/controllers/crops_controller.rb
require 'will_paginate/array'

class CropsController < ApplicationController
  before_filter :authenticate_member!, :except => [:index, :hierarchy, :search, :show]
  load_and_authorize_resource
  skip_authorize_resource :only => [:hierarchy, :search]

  # GET /crops
  # GET /crops.json
  def index
    @sort = params[:sort]
    if @sort == 'alpha'
      # alphabetical order
      @crops = Crop.includes(:scientific_names, {:plantings => :photos})
      @paginated_crops = @crops.approved.paginate(:page => params[:page])
    else
      # default to sorting by popularity
      @crops = Crop.popular.includes(:scientific_names, {:plantings => :photos})
      @paginated_crops = @crops.approved.paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html
      format.json { render :json => @crops }
      format.rss do
        @crops = Crop.recent.includes(:scientific_names, :creator)
        render :rss => @crops
      end
      format.csv do
        @filename = "Growstuff-Crops-#{Time.zone.now.to_s(:number)}.csv"
        @crops = Crop.includes(:scientific_names, :plantings, :seeds, :creator)
        render :csv => @crops
      end
    end
  end

  # GET /crops/wrangle
  def wrangle
    @approval_status = params[:approval_status]
    case @approval_status
    when "pending"
      @crops = Crop.pending_approval
    when "rejected"
      @crops = Crop.rejected
    else
      @crops = Crop.recent
    end

    @crops = @crops.paginate(:page => params[:page])

    @crop_wranglers = Role.crop_wranglers
    respond_to do |format|
      format.html
    end
  end

  # GET /crops/hierarchy
  def hierarchy
    @crops = Crop.toplevel
    respond_to do |format|
      format.html
    end
  end

  # GET /crops/search
  def search
    @term = params[:term]
    @matches = Crop.search(@term)
    @paginated_matches = @matches.paginate(:page => params[:page])

    respond_to do |format|
      format.html
      format.json { render :json => @matches }
    end
  end

  # GET /crops/1
  # GET /crops/1.json
  def show
    @crop = Crop.includes(:scientific_names, {:plantings => :photos}).find(params[:id])
    @posts = @crop.posts.paginate(:page => params[:page])

    respond_to do |format|
      format.html # show.html.haml
      format.json do
        render :json => @crop.to_json(:include => {
          :plantings => { :include => { :owner => { :only => [:id, :login_name, :location, :latitude, :longitude] }}}
        })
      end
    end
  end

  # GET /crops/new
  # GET /crops/new.json
  def new
    @crop = Crop.new
    @crop.alternate_names.build
    @crop.scientific_names.build

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @crop }
    end
  end

  # GET /crops/1/edit
  def edit
    @crop = Crop.find(params[:id])
    @crop.alternate_names.build if @crop.alternate_names.blank?
    @crop.scientific_names.build if @crop.scientific_names.blank?

  end

  # POST /crops
  # POST /crops.json
  def create

    @crop = Crop.new(crop_params)

    if current_member.has_role? :crop_wrangler
      @crop.creator = current_member
      success_msg = "Crop was successfully created."
    else
      @crop.requester = current_member
      @crop.approval_status = "pending"
      success_msg = "Crop was successfully requested."
    end

    respond_to do |format|
      if @crop.save
        params[:alt_name].each do |index, value|
        @crop.alternate_names.create(name: value, creator_id: current_member.id)
        end
        params[:sci_name].each do |index, value|
        @crop.scientific_names.create(scientific_name: value, creator_id: current_member.id)
        end
        unless current_member.has_role? :crop_wrangler
          Role.crop_wranglers.each do |w|
            Notifier.new_crop_request(w, @crop).deliver!
          end
        end

        format.html { redirect_to @crop, notice: success_msg }
        format.json { render json: @crop, status: :created, location: @crop }
      else
        format.html { render action: "new" }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crops/1
  # PUT /crops/1.json
  def update
    @crop = Crop.find(params[:id])

    previous_status = @crop.approval_status

    @crop.creator = current_member if previous_status == "pending"

    respond_to do |format|
      if @crop.update(crop_params)
        if !params[:alt_name].nil?
          @crop.alternate_names.each do |alt_name|
            alt_name.destroy
          end

          params[:alt_name].each do |index, value|
            alt_name = @crop.alternate_names.create(name: value, creator_id: current_member.id)
          end

          @crop.scientific_names.each do |sci_name|
            sci_name.destroy
          end
          params[:sci_name].each do |index, value|
            sci_name = @crop.scientific_names.create(scientific_name: value, creator_id: current_member.id)
          end
        end
        
        if previous_status == "pending"
          requester = @crop.requester
          new_status = @crop.approval_status
          Notifier.crop_request_approved(requester, @crop).deliver! if new_status == "approved"
          Notifier.crop_request_rejected(requester, @crop).deliver! if new_status == "rejected"
        end
        format.html { redirect_to @crop, notice: 'Crop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crops/1
  # DELETE /crops/1.json
  def destroy
    @crop = Crop.find(params[:id])
    @crop.destroy

    respond_to do |format|
      format.html { redirect_to crops_url }
      format.json { head :no_content }
    end
  end

  private

  def crop_params
    params.require(:crop).permit(:en_wikipedia_url, :name, :parent_id, :creator_id, :approval_status, :request_notes, :reason_for_rejection, :rejection_notes, :scientific_names_attributes => [:scientific_name, :_destroy, :id])
  end
end

app/helpers/crops_helper.rb
module CropsHelper
  def display_seed_availability(member, crop)
    total_quantity = 0
    member.seeds.each do |seed|
      if seed.crop.name == crop.name
        total_quantity = total_quantity + seed.quantity
      end
    end

    if (total_quantity != 0)
      "You have #{pluralize(total_quantity, "seed")} of this crop."
    else
      "You don't have any seeds of this crop."
    end
  
  end
end

app/views/crops/_alternate_names.html.haml
.alternate_names
  %h4 Alternate names
  - if crop.alternate_names.empty?
    %p None known.
  - else
    %ul
      - crop.alternate_names.each do |an|
        %li
          = an.name
          - if can? :edit, an
            = link_to 'Edit', edit_alternate_name_path(an), { :class => 'btn btn-default btn-xs' }
          - if can? :destroy, an
            = link_to 'Delete', an, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-xs'
  %p
  - if can? :edit, crop
    = link_to 'Add', new_alternate_name_path( :crop_id => crop.id ), { :class => 'btn btn-default btn-xs' }

app/views/crops/_hierarchy.html.haml
%ul
  - @count ||= 0
  - unless defined? max
    - max = 0 # list all without "show all" toggle button
  - display_crops.each do |c|
    %li.crop-hierarchy{:class => max != 0 && @count >= max ? ['hide', 'toggle'] : []}
      = link_to c, c
      - @count += 1
      - if c.varieties.present?
        - c.varieties.each do |v|
          = render :partial => 'hierarchy', :locals => { :display_crops => [ v ], :max => max }

app/views/crops/_image_with_popover.html.haml
- cache crop do
  = link_to |
    image_tag( |
      crop.default_photo ?  crop.default_photo.thumbnail_url : 'placeholder_150.png', |
      :alt => crop.name, |
      :class => 'image-responsive crop-image' |
    ), |
    crop, |
    :rel => "popover", |
    'data-trigger' => 'hover', |
    'data-title' => crop.name, |
    'data-content' => "#{ render :partial => 'crops/popover', :locals => { :crop => crop } }", |
    'data-html' => true |

app/views/crops/_index_card.html.haml
.well
  .row
    .col-md-4
      = link_to image_tag((crop.default_photo ? crop.default_photo.thumbnail_url : 'placeholder_150.png'), :alt => '', :class => 'img crop-image'), crop
    .col-md-8
      %h3{:style => 'padding-top: 0px; margin-top: 0px'}
        = link_to crop, crop

      %p
        %b Scientific name:
        = crop.default_scientific_name
      %p
        %b
          Planted
          = pluralize(crop.plantings.size, "time")
        by #{ENV['GROWSTUFF_SITE_NAME']} members

      - if can? :create, Planting
        = link_to 'Plant this', new_planting_path(:params => { :crop_id => crop.id }), :class => 'btn btn-primary'
      - if can? :create, Seed
        = link_to 'Add seeds to stash', new_seed_path(:params => { :crop_id => crop.id }), :class => 'btn btn-primary'

app/views/crops/_planting_advice.html.haml
%p
  %strong Plant from:
  - if crop.planted_from.empty?
    not known.
  - else
    - planted_from = crop.planted_from.sort_by {|s, freq| freq }.reverse
    = planted_from.map {|s, freq| "#{s} (#{freq})" }.join(", ")

%p
  %strong Plant in:
  - if crop.sunniness.empty?
    not known.
  - else
    - sunniness = crop.sunniness.sort_by {|s, freq| freq }.reverse
    = sunniness.map {|s, freq| "#{s} (#{freq})" }.join(", ")

app/views/crops/_plantings.html.haml
%h4 See who's planted #{ crop.name.pluralize }
- if crop.plantings.empty?
  %p
    Nobody has planted this crop yet.
- else
  %ul
    - crop.plantings.take(3).each do |planting|
      %li
        = link_to display_planting(planting), planting_path(planting)
        = render :partial => 'members/location', :locals => { :member => planting.owner }
        %small
          = distance_of_time_in_words(planting.created_at, Time.zone.now)
          ago.
  %p
    = link_to "View all #{crop.name} plantings", plantings_by_crop_path(crop)
- if crop.approved?
  - if current_member
    %p= link_to "Plant #{crop.name}", new_planting_path(:crop_id => crop.id)
  - else
    = render :partial => 'shared/signin_signup', :locals => { :to => "track your #{crop.name} plantings" }

app/views/crops/_popover.html.haml
%p
  %small
    - if crop.scientific_names.size > 0
      %i
        = crop.scientific_names.first.scientific_name
    %br/
    Planted
    = pluralize(crop.plantings.size, "time")

app/views/crops/_varieties.html.haml
.varieties
  - if crop.parent
    %p
      = crop.name
      is a variety of
      = succeed "." do
        = link_to crop.parent, crop.parent

  - unless crop.varieties.empty?
    %p
      Varieties of #{crop.name}:

    - max = 5
    = render :partial => 'hierarchy', :locals => { :display_crops => [ crop ], :max => max }
    - if max != 0 && @count > max
      = button_tag "Show all #{@count-1} varieties", :class => 'btn btn-link toggle crop-hierarchy'
      = button_tag "Show less varieties", :class => 'btn btn-link toggle crop-hierarchy hide'

  - if ! crop.parent and crop.varieties.empty?
    %p None known.

app/views/crops/_wrangle.html.haml
- if can? :edit, crop or can? :destroy, crop
  %h4 Crop wrangling
  %p
    You are a
    = succeed "." do
      %strong CROP WRANGLER
  %p
    - if can? :edit, crop
      = link_to 'Edit crop', edit_crop_path(crop), { :class => 'btn btn-default btn-xs' }
    - if can? :destroy, crop
      = link_to 'Delete crop', crop, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-xs'

app/views/crops/edit.html.haml
- content_for :title, "Edit crop: #{@crop.name}"

- if @crop.approval_status == "approved"
  - if @crop.requester
    %p Requested by #{link_to @crop.requester, @crop.requester} #{distance_of_time_in_words(@crop.created_at, Time.zone.now)} ago.
    %p Approved by #{link_to @crop.creator, @crop.creator}.
  - else
    %p Added by #{link_to @crop.creator, @crop.creator} #{distance_of_time_in_words(@crop.created_at, Time.zone.now)} ago.
- elsif @crop.approval_status == "pending"
  .alert.alert-danger
    %p Requested by #{link_to @crop.requester, @crop.requester} #{distance_of_time_in_words(@crop.created_at, Time.zone.now)} ago.
    %p Status: #{@crop.approval_status}.
- elsif @crop.approval_status == "rejected"
  .alert.alert-danger
    %p Requested by #{link_to @crop.requester, @crop.requester} #{distance_of_time_in_words(@crop.created_at, Time.zone.now)} ago.
    %p Status: #{@crop.approval_status} by #{link_to @crop.creator, @crop.creator}.

= render 'form'

app/views/crops/hierarchy.html.haml
- content_for :title, "Crop Hierarchy"

%p
  This page shows the hierarchical tree of all crops in our
  = succeed "." do
    = link_to "crops database", crops_path

- cache cache_key_for(Crop) do
  = render :partial => "hierarchy", :locals => { :display_crops => @crops }

app/views/crops/index.html.haml
- content_for :title, t('.title')
- content_for :subtitle, t('.subtitle', crops_size: @crops.size)

- if can? :wrangle, Crop
  = link_to 'Wrangle Crops', wrangle_crops_path, :class => 'btn btn-primary'
%p
  #{ENV['GROWSTUFF_SITE_NAME']} tracks who's growing what, where.
  View any crop page to see which of our members have planted it and find
  information on how to grow it yourself.

= form_tag(crops_path, :method => :get, :class => 'form-inline', :role => 'form') do
  .form-group
    = label_tag :sort, "Sort by:", :class => 'sr-only'
    = select_tag "sort", options_for_select({"Sort by popularity" => 'popular', "Sort alphabetically" => 'alpha'}, @sort || 'popular'), :class => 'form-control'
  = submit_tag "Show", :class => 'btn btn-primary'

%div.pagination
  = will_paginate @paginated_crops

.row
  - @paginated_crops.each do |crop|
    .col-md-2.six-across
      = render :partial => "thumbnail", :locals => { :crop => crop }

- if can? :create, Crop
  %div
    = link_to 'New Crop', new_crop_path, {:class => 'btn btn-primary'}

%div.pagination
  = will_paginate @paginated_crops


%ul.list-inline
  %li The data on this page is available in the following formats:
  %li= link_to "CSV", crops_path(:format => 'csv')
  %li= link_to "JSON", crops_path(:format => 'json')
  %li= link_to "RSS", crops_path(:format => 'rss')

app/views/crops/index.rss.haml
<?xml version="1.0" encoding="UTF-8"?>
%rss{:version => 2.0}
  %channel
    %title Recently added crops (#{ENV['GROWSTUFF_SITE_NAME']})
    %link= crops_url
    - @crops.each do |crop|
      %item
        %title= crop.name
        %pubDate= crop.created_at.to_s(:rfc822)
        %link= post_url(crop)
        %guid= post_url(crop)

app/views/crops/search.html.haml
- if @term
  - content_for :title, "Crops matching \"#{@term}\""
  - if @matches
    - content_for :subtitle, "#{@matches.size} total"
- else
  - content_for :title, "Crop search"

%div
  = form_tag crops_search_path, :method => :get, :id => 'crop-search', :class => 'form-inline' do
    .form-group
      = label_tag :term, "Search crops:", :class => 'sr-only'
      = text_field_tag 'term', nil, :class => 'search-query input-medium form-control', :placeholder => 'Search crops', :value => @term
    = submit_tag "Search", :class => 'btn btn-primary'

- if @matches.empty?
  %h2 No results found
  %p
    Sorry, we couldn't find any crops that matched your search for "#{@term}".
  %p
    Try
    = link_to "browsing our crop database", crops_path
    instead.

- else
  %div.pagination
    = will_paginate @paginated_matches

  %div#paginated_matches
    .row
      - @paginated_matches.each do |c|
        .col-md-2.six-across
          = render :partial => "thumbnail", :locals => { :crop => c }

  %div.pagination
    = will_paginate @paginated_matches